version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: folior-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    restart: unless-stopped
    networks:
      - folior-network

  frontend:
    build:
      context: ./frontend
    container_name: folior-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - folior-network

networks:
  folior-network:
    driver: bridge
