name: Maven Build & Test

on:
  push:
    branches: [ main, dev ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ main, dev ]
    paths:
      - 'backend/**'

jobs:
  build:
    name: Build and test backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        cache-dependency-path: backend/pom.xml
    
    - name: Build and test with Maven
      run: ./mvnw -B verify
      
    - name: Upload test reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: backend-test-reports
        path: backend/target/surefire-reports/
        retention-days: 5
